model: 'GCFL+dWs'
device: 'cpu'
num_repeat: 1
repeat: None
num_rounds: 200
local_epoch: 1
lr: 0.001
weight_decay: 0.0005
nlayer: 3
hidden: 64
dropout: 0.5
batch_size: 128
seed: 10
datapath: './data'
outbase: './outputs'
convert_x: False
num_clients: 10
overlap: False
standardize: False
seq_length: 5
epsilon1: 0.05
epsilon2: 0.1